### ISSUE TITLE
Quit after rewinding failure

### ISSUE THREAD

**Issue by haishanh** [Wiredcraft/kue-jm#1]
Currently, if rewind task failed it doesn't stop. There is also a potential access invalid array index bug at https://github.com/Wiredcraft/kue-jm/blob/master/lib/taskSeries.js#L47 while rewinding.

Instead we should:

 * [x] quit after rewinding failure
 * [x] split normal execution flow and rewind execution flow into 2 parts for simplicity's sake.

**Comment by xavierchow** [comment]
@ChopperLee2011 pls follow up

**Comment by ChopperLee2011** [comment]
this issue is fixed, closing.
