### ISSUE TITLE
Promise warning

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/kue-jm#2]
```
 (node:14985) Warning: a promise was created in a handler at /var/lib/strong-pm/svc/1/work/{some-hash}/node_modules/kue-jm/lib/jobManager.js:72:14 but was not returned from it, see http://goo.gl/rRqMUw
```

**Comment by ChopperLee2011** [comment]
seem that using the callback style job handler code here  https://github.com/Wiredcraft/kue-jm/blob/master/lib/jobManager.js#L55 within a promise maybe invoke this warning, i will try to wrap up all to promise style and let's see.

**Comment by ChopperLee2011** [comment]
done, closing
